[book]
authors = ["eraflo"]
language = "en"
src = "src"
title = "Khora Engine Documentation"

[output.html]
site-url = "/KhoraEngine/"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 0

[preprocessor.mermaid]
command = "mdbook-mermaid"
  